syntax = "proto3";

package proto;

option go_package = "gate4/pkg/pb";

import "common.proto";
import "users.proto";

service Accounts {
    rpc ListUserAccounts(UserID) returns (AccountList);
    rpc CreateAccount(Account) returns (Account);
    rpc GetAccount(AccountID) returns (Account);
    rpc DeleteAccount(AccountID) returns (EmptyMessage);
    rpc UpdateAccount(Account) returns (EmptyMessage);
}

message Account {
    string id      = 1;
    string user_id = 2;
    string broker  = 3;
    int64 created  = 4;
    int64 expires  = 5;
    optional bytes credentials = 6;
}

message AccountList {
  repeated Account accounts = 1;
}

message AccountID {
  string account_id = 1;
}