syntax = "proto3";

package proto;

option go_package = "gate4/pkg/pb";


message GetPositionsResponse {
  repeated Position positions = 1;
}

message Position {
  string symbol = 1;
  string price = 2;
  string size = 3; // size sign is direction (+ long / - short)
  string profit = 4;
}

message QuoteStreamRequest {
  string account_key = 1;
  string symbol = 2;
}

message QuoteStreamResponse {
  string symbol = 1;
  int64 timestamp = 2;
  string ask = 3;
  string bid = 4;
}

message GetScheduleRequest {
  string account_key = 1;
  string symbol = 2;
}

message GetScheduleResponse {
  repeated ScheduleSession sessions = 2;
}

message ScheduleSession {
  string type = 1;
  int64 start = 2;
  int64 end = 3;
}

message AccountTradeResponse {
  int64 timestamp = 1;
	string account_id = 2;
	string symbol = 3;
  string price = 4;
	string size = 5;
}

message GetAssetRequest {
  string account_key = 1;
  string symbol = 2;
}

message GetAssetResponse {
  string symbol = 1;
	string description = 2;     
	int32 decimals = 3;
	string min_step = 4;
	string lot_size = 5;  
	string currency = 6; 
}