syntax = "proto3";

package proto;

option go_package = "gate4/pkg/pb";

service Gate4 {
  // users managment
  rpc ListUsers(EmptyMessage) returns (ListUsersResponse);
  rpc CreateUser(User) returns (User);
  rpc FindUser(UserID) returns (User);
  rpc DeleteUser(UserID) returns (EmptyMessage);
  rpc BlockUser(BlockUserRequest) returns (EmptyMessage);
  rpc UpdateUser(UpdateUserRequest) returns (User);
  rpc CreateCert(CreateCertRequest) returns (CreateCertResponse);

  // broker commands
  rpc SubscribeQuotes(SymbolRequest) returns (stream Quote);
}

message EmptyMessage {}

message User {
  string broker_id = 1;
  string account_id = 2;
  int64 created = 3;
  int64 expires = 4;
  bool blocked = 5;
  optional string secret = 6;
  optional string id = 7;
}

message CreateCertRequest {
  string common_name = 1;
  string private_key = 2;
}

message CreateCertResponse {
  string cert = 1;
}

message ListUsersResponse {
  repeated User users = 1;
}

message BlockUserRequest {
  string user_id = 1;
  bool blocked = 2;
}

message UpdateUserRequest {
  string user_id = 1;
  string secret = 2;
  int64 expires = 3;
}

message UserID {
  string user_id = 1;
}

message SymbolRequest {
  string user_id = 1;
  string symbol = 2;
}

message Quote {
  string symbol = 1;
  int64 timestamp = 2;
  repeated string ask_price = 3;
  repeated string bid_price = 4;
  repeated string ask_size = 5;
  repeated string bid_size = 6;
}