syntax = "proto3";

package proto;

option go_package = "gate4/pkg/pb";

service Admin {
  rpc ListUsers(EmptyMessage) returns (ListUsersResponse) {}
  rpc AddUser(User) returns (UserID) {}
  rpc FindUser(UserID) returns (User) {}
  rpc DeleteUser(UserID) returns (EmptyMessage) {}
  rpc BlockUser(BlockUserRequest) returns (EmptyMessage) {}
  rpc UpdateUser(UpdateUserRequest) returns (EmptyMessage) {}
}

message EmptyMessage {}

message User {
  string broker_id = 1;
  string account_id = 2;
  int64 valid_until = 3;
  bool blocked = 4;
  optional string secret = 5;
  optional string id = 6;
}

message ListUsersResponse {
  repeated User users = 1;
}

message BlockUserRequest {
  string user_id = 1;
  bool blocked = 2;
}

message UpdateUserRequest {
  string user_id = 1;
  string secret = 2;
  int64 valid_until = 3;
}

message UserID {
  string user_id = 1;
}