syntax = "proto3";

package proto;

option go_package = "gate4/pkg/pb";

import "gateway.proto";
import "admin.proto";

service Gateway {
  rpc GetPositions(AccountRequest) returns (GetPositionsResponse) {}
  rpc SubscribeQuoutes(QuoteStreamRequest) returns (stream QuoteStreamResponse);
}

service Admin {
  rpc ListAccounts(EmptyMessage) returns (ListAccountsResponse) {}
  rpc AddAccount(AddAccountRequest) returns (EmptyMessage) {}
  rpc DeleteAccount(AccountRequest) returns (EmptyMessage) {}
  rpc GetPositions(AccountRequest) returns (GetPositionsResponse) {}
  rpc SubscribeQuoutes(QuoteStreamRequest) returns (stream QuoteStreamResponse);
  rpc GetSchedule(GetScheduleRequest) returns (GetScheduleResponse) {}
  rpc SubscribeAccountTrades(AccountRequest) returns (stream AccountTradeResponse);
  rpc GetAsset(GetAssetRequest) returns (GetAssetResponse) {}
}