syntax = "proto3";

package proto;

option go_package = "gate4/pkg/pb";

import "gateway.proto";
import "admin.proto";

service Gateway {
  rpc GetAccountInfo(AccountRequest) returns (AccountResponse) {}
}

service Admin {
  rpc ListAccounts(EmptyMessage) returns (ListAccountsResponse) {}
  rpc AddAccount(AddAccountRequest) returns (EmptyMessage) {}
  rpc DeleteAccount(AccountRequest) returns (EmptyMessage) {}
  rpc GetPositions(AccountRequest) returns (GetPositionsResponse) {}
  rpc QuoteStream(QuoteStreamRequest) returns (stream QuoteStreamResponse);
}