syntax = "proto3";

package proto;

option go_package = "gate4/pkg/pb";

import "gateway.proto";
import "admin.proto";

service Gateway {
  rpc GetPosition(SymbolRequest) returns (Position) {}
  rpc SubscribeQuoutes(SymbolRequest) returns (stream QuoteStreamResponse);
}

service Admin {
  rpc ListAccounts(EmptyMessage) returns (ListAccountsResponse) {}
  rpc AddAccount(AddAccountRequest) returns (EmptyMessage) {}
  rpc DeleteAccount(AccountRequest) returns (EmptyMessage) {}
  rpc GetPositions(AccountRequest) returns (ListPositions) {}
  rpc GetPosition(SymbolRequest) returns (Position) {}
  rpc SubscribeQuoutes(SymbolRequest) returns (stream QuoteStreamResponse);
  rpc GetSchedule(SymbolRequest) returns (GetScheduleResponse) {}
  rpc SubscribeAccountTrades(AccountRequest) returns (stream AccountTradeResponse);
  rpc GetAsset(SymbolRequest) returns (GetAssetResponse) {}
}