syntax = "proto3";

package proto;

option go_package = "gate4/pkg/pb";

import "common.proto";

service Users {
    rpc ListUsers(EmptyMessage) returns (UserList);
    rpc CreateUser(User) returns (User);
    rpc GetUser(UserID) returns (User);
    rpc FindUserByID(UserID) returns (User);
    rpc DeleteUser(UserID) returns (EmptyMessage);
    rpc UpdateUser(User) returns (EmptyMessage);
    rpc CreateCert(CreateCertRequest) returns (CreateCertResponse);
}

message User {
    string id       = 1;
    string name     = 2;
    string email    = 3;
    int64 created   = 4;
    bool blocked    = 5;
    string role     = 6;
}

message UserList {
  repeated User users = 1;
}

message UserID {
  string user_id = 1;
}

message CreateCertRequest {
    string user_id = 1;
    string public_key = 2;
}

message CreateCertResponse {
  string cert = 1;
}