// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: accounts.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Broker        string                 `protobuf:"bytes,3,opt,name=broker,proto3" json:"broker,omitempty"`
	Created       int64                  `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Expires       int64                  `protobuf:"varint,5,opt,name=expires,proto3" json:"expires,omitempty"`
	Credentials   []byte                 `protobuf:"bytes,6,opt,name=credentials,proto3,oneof" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_accounts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Account) GetBroker() string {
	if x != nil {
		return x.Broker
	}
	return ""
}

func (x *Account) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *Account) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *Account) GetCredentials() []byte {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type AccountList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountList) Reset() {
	*x = AccountList{}
	mi := &file_accounts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountList) ProtoMessage() {}

func (x *AccountList) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountList.ProtoReflect.Descriptor instead.
func (*AccountList) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *AccountList) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type AccountID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountID) Reset() {
	*x = AccountID{}
	mi := &file_accounts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountID) ProtoMessage() {}

func (x *AccountID) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountID.ProtoReflect.Descriptor instead.
func (*AccountID) Descriptor() ([]byte, []int) {
	return file_accounts_proto_rawDescGZIP(), []int{2}
}

func (x *AccountID) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

var File_accounts_proto protoreflect.FileDescriptor

const file_accounts_proto_rawDesc = "" +
	"\n" +
	"\x0eaccounts.proto\x12\x05proto\x1a\fcommon.proto\x1a\vusers.proto\"\xb5\x01\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06broker\x18\x03 \x01(\tR\x06broker\x12\x18\n" +
	"\acreated\x18\x04 \x01(\x03R\acreated\x12\x18\n" +
	"\aexpires\x18\x05 \x01(\x03R\aexpires\x12%\n" +
	"\vcredentials\x18\x06 \x01(\fH\x00R\vcredentials\x88\x01\x01B\x0e\n" +
	"\f_credentials\"9\n" +
	"\vAccountList\x12*\n" +
	"\baccounts\x18\x01 \x03(\v2\x0e.proto.AccountR\baccounts\"*\n" +
	"\tAccountID\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId2\x90\x02\n" +
	"\bAccounts\x125\n" +
	"\x10ListUserAccounts\x12\r.proto.UserID\x1a\x12.proto.AccountList\x12/\n" +
	"\rCreateAccount\x12\x0e.proto.Account\x1a\x0e.proto.Account\x12.\n" +
	"\n" +
	"GetAccount\x12\x10.proto.AccountID\x1a\x0e.proto.Account\x126\n" +
	"\rDeleteAccount\x12\x10.proto.AccountID\x1a\x13.proto.EmptyMessage\x124\n" +
	"\rUpdateAccount\x12\x0e.proto.Account\x1a\x13.proto.EmptyMessageB\x0eZ\fgate4/pkg/pbb\x06proto3"

var (
	file_accounts_proto_rawDescOnce sync.Once
	file_accounts_proto_rawDescData []byte
)

func file_accounts_proto_rawDescGZIP() []byte {
	file_accounts_proto_rawDescOnce.Do(func() {
		file_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounts_proto_rawDesc), len(file_accounts_proto_rawDesc)))
	})
	return file_accounts_proto_rawDescData
}

var file_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_accounts_proto_goTypes = []any{
	(*Account)(nil),      // 0: proto.Account
	(*AccountList)(nil),  // 1: proto.AccountList
	(*AccountID)(nil),    // 2: proto.AccountID
	(*UserID)(nil),       // 3: proto.UserID
	(*EmptyMessage)(nil), // 4: proto.EmptyMessage
}
var file_accounts_proto_depIdxs = []int32{
	0, // 0: proto.AccountList.accounts:type_name -> proto.Account
	3, // 1: proto.Accounts.ListUserAccounts:input_type -> proto.UserID
	0, // 2: proto.Accounts.CreateAccount:input_type -> proto.Account
	2, // 3: proto.Accounts.GetAccount:input_type -> proto.AccountID
	2, // 4: proto.Accounts.DeleteAccount:input_type -> proto.AccountID
	0, // 5: proto.Accounts.UpdateAccount:input_type -> proto.Account
	1, // 6: proto.Accounts.ListUserAccounts:output_type -> proto.AccountList
	0, // 7: proto.Accounts.CreateAccount:output_type -> proto.Account
	0, // 8: proto.Accounts.GetAccount:output_type -> proto.Account
	4, // 9: proto.Accounts.DeleteAccount:output_type -> proto.EmptyMessage
	4, // 10: proto.Accounts.UpdateAccount:output_type -> proto.EmptyMessage
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_accounts_proto_init() }
func file_accounts_proto_init() {
	if File_accounts_proto != nil {
		return
	}
	file_common_proto_init()
	file_users_proto_init()
	file_accounts_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounts_proto_rawDesc), len(file_accounts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accounts_proto_goTypes,
		DependencyIndexes: file_accounts_proto_depIdxs,
		MessageInfos:      file_accounts_proto_msgTypes,
	}.Build()
	File_accounts_proto = out.File
	file_accounts_proto_goTypes = nil
	file_accounts_proto_depIdxs = nil
}
