// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: gate4.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_gate4_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gate4_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_gate4_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerId      string                 `protobuf:"bytes,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Created       int64                  `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Expires       int64                  `protobuf:"varint,4,opt,name=expires,proto3" json:"expires,omitempty"`
	Blocked       bool                   `protobuf:"varint,5,opt,name=blocked,proto3" json:"blocked,omitempty"`
	Secret        *string                `protobuf:"bytes,6,opt,name=secret,proto3,oneof" json:"secret,omitempty"`
	Id            *string                `protobuf:"bytes,7,opt,name=id,proto3,oneof" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_gate4_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_gate4_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_gate4_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetBrokerId() string {
	if x != nil {
		return x.BrokerId
	}
	return ""
}

func (x *User) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *User) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *User) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *User) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *User) GetSecret() string {
	if x != nil && x.Secret != nil {
		return *x.Secret
	}
	return ""
}

func (x *User) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_gate4_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gate4_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_gate4_proto_rawDescGZIP(), []int{2}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type BlockUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Blocked       bool                   `protobuf:"varint,2,opt,name=blocked,proto3" json:"blocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserRequest) Reset() {
	*x = BlockUserRequest{}
	mi := &file_gate4_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserRequest) ProtoMessage() {}

func (x *BlockUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gate4_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserRequest.ProtoReflect.Descriptor instead.
func (*BlockUserRequest) Descriptor() ([]byte, []int) {
	return file_gate4_proto_rawDescGZIP(), []int{3}
}

func (x *BlockUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BlockUserRequest) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Expires       int64                  `protobuf:"varint,3,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_gate4_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gate4_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_gate4_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *UpdateUserRequest) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_gate4_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_gate4_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_gate4_proto_rawDescGZIP(), []int{5}
}

func (x *UserID) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_gate4_proto protoreflect.FileDescriptor

const file_gate4_proto_rawDesc = "" +
	"\n" +
	"\vgate4.proto\x12\x05proto\"\x0e\n" +
	"\fEmptyMessage\"\xd4\x01\n" +
	"\x04User\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\tR\bbrokerId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x18\n" +
	"\aexpires\x18\x04 \x01(\x03R\aexpires\x12\x18\n" +
	"\ablocked\x18\x05 \x01(\bR\ablocked\x12\x1b\n" +
	"\x06secret\x18\x06 \x01(\tH\x00R\x06secret\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\a \x01(\tH\x01R\x02id\x88\x01\x01B\t\n" +
	"\a_secretB\x05\n" +
	"\x03_id\"6\n" +
	"\x11ListUsersResponse\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.proto.UserR\x05users\"E\n" +
	"\x10BlockUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\ablocked\x18\x02 \x01(\bR\ablocked\"^\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x18\n" +
	"\aexpires\x18\x03 \x01(\x03R\aexpires\"!\n" +
	"\x06UserID\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId2\xc1\x02\n" +
	"\x05Admin\x12<\n" +
	"\tListUsers\x12\x13.proto.EmptyMessage\x1a\x18.proto.ListUsersResponse\"\x00\x12(\n" +
	"\n" +
	"CreateUser\x12\v.proto.User\x1a\v.proto.User\"\x00\x12(\n" +
	"\bFindUser\x12\r.proto.UserID\x1a\v.proto.User\"\x00\x122\n" +
	"\n" +
	"DeleteUser\x12\r.proto.UserID\x1a\x13.proto.EmptyMessage\"\x00\x12;\n" +
	"\tBlockUser\x12\x17.proto.BlockUserRequest\x1a\x13.proto.EmptyMessage\"\x00\x125\n" +
	"\n" +
	"UpdateUser\x12\x18.proto.UpdateUserRequest\x1a\v.proto.User\"\x00B\x0eZ\fgate4/pkg/pbb\x06proto3"

var (
	file_gate4_proto_rawDescOnce sync.Once
	file_gate4_proto_rawDescData []byte
)

func file_gate4_proto_rawDescGZIP() []byte {
	file_gate4_proto_rawDescOnce.Do(func() {
		file_gate4_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gate4_proto_rawDesc), len(file_gate4_proto_rawDesc)))
	})
	return file_gate4_proto_rawDescData
}

var file_gate4_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gate4_proto_goTypes = []any{
	(*EmptyMessage)(nil),      // 0: proto.EmptyMessage
	(*User)(nil),              // 1: proto.User
	(*ListUsersResponse)(nil), // 2: proto.ListUsersResponse
	(*BlockUserRequest)(nil),  // 3: proto.BlockUserRequest
	(*UpdateUserRequest)(nil), // 4: proto.UpdateUserRequest
	(*UserID)(nil),            // 5: proto.UserID
}
var file_gate4_proto_depIdxs = []int32{
	1, // 0: proto.ListUsersResponse.users:type_name -> proto.User
	0, // 1: proto.Admin.ListUsers:input_type -> proto.EmptyMessage
	1, // 2: proto.Admin.CreateUser:input_type -> proto.User
	5, // 3: proto.Admin.FindUser:input_type -> proto.UserID
	5, // 4: proto.Admin.DeleteUser:input_type -> proto.UserID
	3, // 5: proto.Admin.BlockUser:input_type -> proto.BlockUserRequest
	4, // 6: proto.Admin.UpdateUser:input_type -> proto.UpdateUserRequest
	2, // 7: proto.Admin.ListUsers:output_type -> proto.ListUsersResponse
	1, // 8: proto.Admin.CreateUser:output_type -> proto.User
	1, // 9: proto.Admin.FindUser:output_type -> proto.User
	0, // 10: proto.Admin.DeleteUser:output_type -> proto.EmptyMessage
	0, // 11: proto.Admin.BlockUser:output_type -> proto.EmptyMessage
	1, // 12: proto.Admin.UpdateUser:output_type -> proto.User
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gate4_proto_init() }
func file_gate4_proto_init() {
	if File_gate4_proto != nil {
		return
	}
	file_gate4_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gate4_proto_rawDesc), len(file_gate4_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gate4_proto_goTypes,
		DependencyIndexes: file_gate4_proto_depIdxs,
		MessageInfos:      file_gate4_proto_msgTypes,
	}.Build()
	File_gate4_proto = out.File
	file_gate4_proto_goTypes = nil
	file_gate4_proto_depIdxs = nil
}
