// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: gate4.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Gate4_ListUsers_FullMethodName  = "/proto.Gate4/ListUsers"
	Gate4_CreateUser_FullMethodName = "/proto.Gate4/CreateUser"
	Gate4_FindUser_FullMethodName   = "/proto.Gate4/FindUser"
	Gate4_DeleteUser_FullMethodName = "/proto.Gate4/DeleteUser"
	Gate4_BlockUser_FullMethodName  = "/proto.Gate4/BlockUser"
	Gate4_UpdateUser_FullMethodName = "/proto.Gate4/UpdateUser"
	Gate4_CreateCert_FullMethodName = "/proto.Gate4/CreateCert"
)

// Gate4Client is the client API for Gate4 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Gate4Client interface {
	ListUsers(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*ListUsersResponse, error)
	CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	FindUser(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*User, error)
	DeleteUser(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*EmptyMessage, error)
	BlockUser(ctx context.Context, in *BlockUserRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error)
	CreateCert(ctx context.Context, in *CreateCertRequest, opts ...grpc.CallOption) (*CreateCertResponse, error)
}

type gate4Client struct {
	cc grpc.ClientConnInterface
}

func NewGate4Client(cc grpc.ClientConnInterface) Gate4Client {
	return &gate4Client{cc}
}

func (c *gate4Client) ListUsers(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, Gate4_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gate4Client) CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, Gate4_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gate4Client) FindUser(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, Gate4_FindUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gate4Client) DeleteUser(ctx context.Context, in *UserID, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, Gate4_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gate4Client) BlockUser(ctx context.Context, in *BlockUserRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, Gate4_BlockUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gate4Client) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, Gate4_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gate4Client) CreateCert(ctx context.Context, in *CreateCertRequest, opts ...grpc.CallOption) (*CreateCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCertResponse)
	err := c.cc.Invoke(ctx, Gate4_CreateCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Gate4Server is the server API for Gate4 service.
// All implementations must embed UnimplementedGate4Server
// for forward compatibility.
type Gate4Server interface {
	ListUsers(context.Context, *EmptyMessage) (*ListUsersResponse, error)
	CreateUser(context.Context, *User) (*User, error)
	FindUser(context.Context, *UserID) (*User, error)
	DeleteUser(context.Context, *UserID) (*EmptyMessage, error)
	BlockUser(context.Context, *BlockUserRequest) (*EmptyMessage, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*User, error)
	CreateCert(context.Context, *CreateCertRequest) (*CreateCertResponse, error)
	mustEmbedUnimplementedGate4Server()
}

// UnimplementedGate4Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGate4Server struct{}

func (UnimplementedGate4Server) ListUsers(context.Context, *EmptyMessage) (*ListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedGate4Server) CreateUser(context.Context, *User) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedGate4Server) FindUser(context.Context, *UserID) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method FindUser not implemented")
}
func (UnimplementedGate4Server) DeleteUser(context.Context, *UserID) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedGate4Server) BlockUser(context.Context, *BlockUserRequest) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method BlockUser not implemented")
}
func (UnimplementedGate4Server) UpdateUser(context.Context, *UpdateUserRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedGate4Server) CreateCert(context.Context, *CreateCertRequest) (*CreateCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCert not implemented")
}
func (UnimplementedGate4Server) mustEmbedUnimplementedGate4Server() {}
func (UnimplementedGate4Server) testEmbeddedByValue()               {}

// UnsafeGate4Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Gate4Server will
// result in compilation errors.
type UnsafeGate4Server interface {
	mustEmbedUnimplementedGate4Server()
}

func RegisterGate4Server(s grpc.ServiceRegistrar, srv Gate4Server) {
	// If the following call panics, it indicates UnimplementedGate4Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Gate4_ServiceDesc, srv)
}

func _Gate4_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Gate4Server).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gate4_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Gate4Server).ListUsers(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate4_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Gate4Server).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gate4_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Gate4Server).CreateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate4_FindUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Gate4Server).FindUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gate4_FindUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Gate4Server).FindUser(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate4_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Gate4Server).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gate4_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Gate4Server).DeleteUser(ctx, req.(*UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate4_BlockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Gate4Server).BlockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gate4_BlockUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Gate4Server).BlockUser(ctx, req.(*BlockUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate4_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Gate4Server).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gate4_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Gate4Server).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate4_CreateCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Gate4Server).CreateCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gate4_CreateCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Gate4Server).CreateCert(ctx, req.(*CreateCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gate4_ServiceDesc is the grpc.ServiceDesc for Gate4 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gate4_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Gate4",
	HandlerType: (*Gate4Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUsers",
			Handler:    _Gate4_ListUsers_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _Gate4_CreateUser_Handler,
		},
		{
			MethodName: "FindUser",
			Handler:    _Gate4_FindUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Gate4_DeleteUser_Handler,
		},
		{
			MethodName: "BlockUser",
			Handler:    _Gate4_BlockUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Gate4_UpdateUser_Handler,
		},
		{
			MethodName: "CreateCert",
			Handler:    _Gate4_CreateCert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gate4.proto",
}
