// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: gate4.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_gate4_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gate4_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_gate4_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerId      string                 `protobuf:"bytes,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Created       int64                  `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Expires       int64                  `protobuf:"varint,4,opt,name=expires,proto3" json:"expires,omitempty"`
	Blocked       bool                   `protobuf:"varint,5,opt,name=blocked,proto3" json:"blocked,omitempty"`
	Secret        *string                `protobuf:"bytes,6,opt,name=secret,proto3,oneof" json:"secret,omitempty"`
	Id            *string                `protobuf:"bytes,7,opt,name=id,proto3,oneof" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_gate4_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_gate4_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_gate4_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetBrokerId() string {
	if x != nil {
		return x.BrokerId
	}
	return ""
}

func (x *User) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *User) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *User) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *User) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *User) GetSecret() string {
	if x != nil && x.Secret != nil {
		return *x.Secret
	}
	return ""
}

func (x *User) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

type CreateCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommonName    string                 `protobuf:"bytes,1,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCertRequest) Reset() {
	*x = CreateCertRequest{}
	mi := &file_gate4_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCertRequest) ProtoMessage() {}

func (x *CreateCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gate4_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCertRequest.ProtoReflect.Descriptor instead.
func (*CreateCertRequest) Descriptor() ([]byte, []int) {
	return file_gate4_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCertRequest) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *CreateCertRequest) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type CreateCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cert          string                 `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCertResponse) Reset() {
	*x = CreateCertResponse{}
	mi := &file_gate4_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCertResponse) ProtoMessage() {}

func (x *CreateCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gate4_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCertResponse.ProtoReflect.Descriptor instead.
func (*CreateCertResponse) Descriptor() ([]byte, []int) {
	return file_gate4_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCertResponse) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_gate4_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gate4_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_gate4_proto_rawDescGZIP(), []int{4}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type BlockUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Blocked       bool                   `protobuf:"varint,2,opt,name=blocked,proto3" json:"blocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserRequest) Reset() {
	*x = BlockUserRequest{}
	mi := &file_gate4_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserRequest) ProtoMessage() {}

func (x *BlockUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gate4_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserRequest.ProtoReflect.Descriptor instead.
func (*BlockUserRequest) Descriptor() ([]byte, []int) {
	return file_gate4_proto_rawDescGZIP(), []int{5}
}

func (x *BlockUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BlockUserRequest) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Expires       int64                  `protobuf:"varint,3,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_gate4_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gate4_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_gate4_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *UpdateUserRequest) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_gate4_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_gate4_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_gate4_proto_rawDescGZIP(), []int{7}
}

func (x *UserID) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SymbolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolRequest) Reset() {
	*x = SymbolRequest{}
	mi := &file_gate4_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolRequest) ProtoMessage() {}

func (x *SymbolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gate4_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolRequest.ProtoReflect.Descriptor instead.
func (*SymbolRequest) Descriptor() ([]byte, []int) {
	return file_gate4_proto_rawDescGZIP(), []int{8}
}

func (x *SymbolRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SymbolRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type Quote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AskPrice      []string               `protobuf:"bytes,3,rep,name=ask_price,json=askPrice,proto3" json:"ask_price,omitempty"`
	BidPrice      []string               `protobuf:"bytes,4,rep,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`
	AskSize       []string               `protobuf:"bytes,5,rep,name=ask_size,json=askSize,proto3" json:"ask_size,omitempty"`
	BidSize       []string               `protobuf:"bytes,6,rep,name=bid_size,json=bidSize,proto3" json:"bid_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_gate4_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_gate4_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_gate4_proto_rawDescGZIP(), []int{9}
}

func (x *Quote) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Quote) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Quote) GetAskPrice() []string {
	if x != nil {
		return x.AskPrice
	}
	return nil
}

func (x *Quote) GetBidPrice() []string {
	if x != nil {
		return x.BidPrice
	}
	return nil
}

func (x *Quote) GetAskSize() []string {
	if x != nil {
		return x.AskSize
	}
	return nil
}

func (x *Quote) GetBidSize() []string {
	if x != nil {
		return x.BidSize
	}
	return nil
}

var File_gate4_proto protoreflect.FileDescriptor

const file_gate4_proto_rawDesc = "" +
	"\n" +
	"\vgate4.proto\x12\x05proto\"\x0e\n" +
	"\fEmptyMessage\"\xd4\x01\n" +
	"\x04User\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\tR\bbrokerId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x18\n" +
	"\aexpires\x18\x04 \x01(\x03R\aexpires\x12\x18\n" +
	"\ablocked\x18\x05 \x01(\bR\ablocked\x12\x1b\n" +
	"\x06secret\x18\x06 \x01(\tH\x00R\x06secret\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\a \x01(\tH\x01R\x02id\x88\x01\x01B\t\n" +
	"\a_secretB\x05\n" +
	"\x03_id\"U\n" +
	"\x11CreateCertRequest\x12\x1f\n" +
	"\vcommon_name\x18\x01 \x01(\tR\n" +
	"commonName\x12\x1f\n" +
	"\vprivate_key\x18\x02 \x01(\tR\n" +
	"privateKey\"(\n" +
	"\x12CreateCertResponse\x12\x12\n" +
	"\x04cert\x18\x01 \x01(\tR\x04cert\"6\n" +
	"\x11ListUsersResponse\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.proto.UserR\x05users\"E\n" +
	"\x10BlockUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\ablocked\x18\x02 \x01(\bR\ablocked\"^\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x18\n" +
	"\aexpires\x18\x03 \x01(\x03R\aexpires\"!\n" +
	"\x06UserID\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\rSymbolRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\"\xad\x01\n" +
	"\x05Quote\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\task_price\x18\x03 \x03(\tR\baskPrice\x12\x1b\n" +
	"\tbid_price\x18\x04 \x03(\tR\bbidPrice\x12\x19\n" +
	"\bask_size\x18\x05 \x03(\tR\aaskSize\x12\x19\n" +
	"\bbid_size\x18\x06 \x03(\tR\abidSize2\xb1\x03\n" +
	"\x05Gate4\x12:\n" +
	"\tListUsers\x12\x13.proto.EmptyMessage\x1a\x18.proto.ListUsersResponse\x12&\n" +
	"\n" +
	"CreateUser\x12\v.proto.User\x1a\v.proto.User\x12&\n" +
	"\bFindUser\x12\r.proto.UserID\x1a\v.proto.User\x120\n" +
	"\n" +
	"DeleteUser\x12\r.proto.UserID\x1a\x13.proto.EmptyMessage\x129\n" +
	"\tBlockUser\x12\x17.proto.BlockUserRequest\x1a\x13.proto.EmptyMessage\x123\n" +
	"\n" +
	"UpdateUser\x12\x18.proto.UpdateUserRequest\x1a\v.proto.User\x12A\n" +
	"\n" +
	"CreateCert\x12\x18.proto.CreateCertRequest\x1a\x19.proto.CreateCertResponse\x127\n" +
	"\x0fSubscribeQuotes\x12\x14.proto.SymbolRequest\x1a\f.proto.Quote0\x01B\x0eZ\fgate4/pkg/pbb\x06proto3"

var (
	file_gate4_proto_rawDescOnce sync.Once
	file_gate4_proto_rawDescData []byte
)

func file_gate4_proto_rawDescGZIP() []byte {
	file_gate4_proto_rawDescOnce.Do(func() {
		file_gate4_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gate4_proto_rawDesc), len(file_gate4_proto_rawDesc)))
	})
	return file_gate4_proto_rawDescData
}

var file_gate4_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_gate4_proto_goTypes = []any{
	(*EmptyMessage)(nil),       // 0: proto.EmptyMessage
	(*User)(nil),               // 1: proto.User
	(*CreateCertRequest)(nil),  // 2: proto.CreateCertRequest
	(*CreateCertResponse)(nil), // 3: proto.CreateCertResponse
	(*ListUsersResponse)(nil),  // 4: proto.ListUsersResponse
	(*BlockUserRequest)(nil),   // 5: proto.BlockUserRequest
	(*UpdateUserRequest)(nil),  // 6: proto.UpdateUserRequest
	(*UserID)(nil),             // 7: proto.UserID
	(*SymbolRequest)(nil),      // 8: proto.SymbolRequest
	(*Quote)(nil),              // 9: proto.Quote
}
var file_gate4_proto_depIdxs = []int32{
	1, // 0: proto.ListUsersResponse.users:type_name -> proto.User
	0, // 1: proto.Gate4.ListUsers:input_type -> proto.EmptyMessage
	1, // 2: proto.Gate4.CreateUser:input_type -> proto.User
	7, // 3: proto.Gate4.FindUser:input_type -> proto.UserID
	7, // 4: proto.Gate4.DeleteUser:input_type -> proto.UserID
	5, // 5: proto.Gate4.BlockUser:input_type -> proto.BlockUserRequest
	6, // 6: proto.Gate4.UpdateUser:input_type -> proto.UpdateUserRequest
	2, // 7: proto.Gate4.CreateCert:input_type -> proto.CreateCertRequest
	8, // 8: proto.Gate4.SubscribeQuotes:input_type -> proto.SymbolRequest
	4, // 9: proto.Gate4.ListUsers:output_type -> proto.ListUsersResponse
	1, // 10: proto.Gate4.CreateUser:output_type -> proto.User
	1, // 11: proto.Gate4.FindUser:output_type -> proto.User
	0, // 12: proto.Gate4.DeleteUser:output_type -> proto.EmptyMessage
	0, // 13: proto.Gate4.BlockUser:output_type -> proto.EmptyMessage
	1, // 14: proto.Gate4.UpdateUser:output_type -> proto.User
	3, // 15: proto.Gate4.CreateCert:output_type -> proto.CreateCertResponse
	9, // 16: proto.Gate4.SubscribeQuotes:output_type -> proto.Quote
	9, // [9:17] is the sub-list for method output_type
	1, // [1:9] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gate4_proto_init() }
func file_gate4_proto_init() {
	if File_gate4_proto != nil {
		return
	}
	file_gate4_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gate4_proto_rawDesc), len(file_gate4_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gate4_proto_goTypes,
		DependencyIndexes: file_gate4_proto_depIdxs,
		MessageInfos:      file_gate4_proto_msgTypes,
	}.Build()
	File_gate4_proto = out.File
	file_gate4_proto_goTypes = nil
	file_gate4_proto_depIdxs = nil
}
