// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x05proto\x1a\raccount.proto\x1a\vadmin.proto2H\n" +
	"\aGateway\x12=\n" +
	"\n" +
	"GetAccount\x12\x15.proto.AccountRequest\x1a\x16.proto.AccountResponse\"\x002\xcf\x01\n" +
	"\x05Admin\x12B\n" +
	"\fListAccounts\x12\x13.proto.EmptyMessage\x1a\x1b.proto.ListAccountsResponse\"\x00\x12=\n" +
	"\n" +
	"AddAccount\x12\x18.proto.AddAccountRequest\x1a\x13.proto.EmptyMessage\"\x00\x12C\n" +
	"\rDeleteAccount\x12\x1b.proto.DeleteAccountRequest\x1a\x13.proto.EmptyMessage\"\x00B\x0eZ\fgate4/pkg/pbb\x06proto3"

var file_service_proto_goTypes = []any{
	(*AccountRequest)(nil),       // 0: proto.AccountRequest
	(*EmptyMessage)(nil),         // 1: proto.EmptyMessage
	(*AddAccountRequest)(nil),    // 2: proto.AddAccountRequest
	(*DeleteAccountRequest)(nil), // 3: proto.DeleteAccountRequest
	(*AccountResponse)(nil),      // 4: proto.AccountResponse
	(*ListAccountsResponse)(nil), // 5: proto.ListAccountsResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: proto.Gateway.GetAccount:input_type -> proto.AccountRequest
	1, // 1: proto.Admin.ListAccounts:input_type -> proto.EmptyMessage
	2, // 2: proto.Admin.AddAccount:input_type -> proto.AddAccountRequest
	3, // 3: proto.Admin.DeleteAccount:input_type -> proto.DeleteAccountRequest
	4, // 4: proto.Gateway.GetAccount:output_type -> proto.AccountResponse
	5, // 5: proto.Admin.ListAccounts:output_type -> proto.ListAccountsResponse
	1, // 6: proto.Admin.AddAccount:output_type -> proto.EmptyMessage
	1, // 7: proto.Admin.DeleteAccount:output_type -> proto.EmptyMessage
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_account_proto_init()
	file_admin_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
