// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x05proto\x1a\raccount.proto\x1a\vadmin.proto2H\n" +
	"\aGateway\x12=\n" +
	"\n" +
	"GetAccount\x12\x15.proto.AccountRequest\x1a\x16.proto.AccountResponse\"\x002\xcb\x01\n" +
	"\x05Admin\x12@\n" +
	"\vListBrokers\x12\x13.proto.EmptyRequest\x1a\x1a.proto.ListBrokersResponse\"\x00\x12<\n" +
	"\tAddBroker\x12\x17.proto.AddBrokerRequest\x1a\x14.proto.EmptyResponse\"\x00\x12B\n" +
	"\fDeleteBroker\x12\x1a.proto.DeleteBrokerRequest\x1a\x14.proto.EmptyResponse\"\x00B\x0eZ\fgate4/pkg/pbb\x06proto3"

var file_service_proto_goTypes = []any{
	(*AccountRequest)(nil),      // 0: proto.AccountRequest
	(*EmptyRequest)(nil),        // 1: proto.EmptyRequest
	(*AddBrokerRequest)(nil),    // 2: proto.AddBrokerRequest
	(*DeleteBrokerRequest)(nil), // 3: proto.DeleteBrokerRequest
	(*AccountResponse)(nil),     // 4: proto.AccountResponse
	(*ListBrokersResponse)(nil), // 5: proto.ListBrokersResponse
	(*EmptyResponse)(nil),       // 6: proto.EmptyResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: proto.Gateway.GetAccount:input_type -> proto.AccountRequest
	1, // 1: proto.Admin.ListBrokers:input_type -> proto.EmptyRequest
	2, // 2: proto.Admin.AddBroker:input_type -> proto.AddBrokerRequest
	3, // 3: proto.Admin.DeleteBroker:input_type -> proto.DeleteBrokerRequest
	4, // 4: proto.Gateway.GetAccount:output_type -> proto.AccountResponse
	5, // 5: proto.Admin.ListBrokers:output_type -> proto.ListBrokersResponse
	6, // 6: proto.Admin.AddBroker:output_type -> proto.EmptyResponse
	6, // 7: proto.Admin.DeleteBroker:output_type -> proto.EmptyResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_account_proto_init()
	file_admin_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
