// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: trading.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Trading_SubscribeQuotes_FullMethodName = "/proto.Trading/SubscribeQuotes"
)

// TradingClient is the client API for Trading service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradingClient interface {
	SubscribeQuotes(ctx context.Context, in *SymbolRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Quote], error)
}

type tradingClient struct {
	cc grpc.ClientConnInterface
}

func NewTradingClient(cc grpc.ClientConnInterface) TradingClient {
	return &tradingClient{cc}
}

func (c *tradingClient) SubscribeQuotes(ctx context.Context, in *SymbolRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Quote], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Trading_ServiceDesc.Streams[0], Trading_SubscribeQuotes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SymbolRequest, Quote]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Trading_SubscribeQuotesClient = grpc.ServerStreamingClient[Quote]

// TradingServer is the server API for Trading service.
// All implementations must embed UnimplementedTradingServer
// for forward compatibility.
type TradingServer interface {
	SubscribeQuotes(*SymbolRequest, grpc.ServerStreamingServer[Quote]) error
	mustEmbedUnimplementedTradingServer()
}

// UnimplementedTradingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradingServer struct{}

func (UnimplementedTradingServer) SubscribeQuotes(*SymbolRequest, grpc.ServerStreamingServer[Quote]) error {
	return status.Error(codes.Unimplemented, "method SubscribeQuotes not implemented")
}
func (UnimplementedTradingServer) mustEmbedUnimplementedTradingServer() {}
func (UnimplementedTradingServer) testEmbeddedByValue()                 {}

// UnsafeTradingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradingServer will
// result in compilation errors.
type UnsafeTradingServer interface {
	mustEmbedUnimplementedTradingServer()
}

func RegisterTradingServer(s grpc.ServiceRegistrar, srv TradingServer) {
	// If the following call panics, it indicates UnimplementedTradingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Trading_ServiceDesc, srv)
}

func _Trading_SubscribeQuotes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SymbolRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TradingServer).SubscribeQuotes(m, &grpc.GenericServerStream[SymbolRequest, Quote]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Trading_SubscribeQuotesServer = grpc.ServerStreamingServer[Quote]

// Trading_ServiceDesc is the grpc.ServiceDesc for Trading service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Trading_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Trading",
	HandlerType: (*TradingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeQuotes",
			Handler:       _Trading_SubscribeQuotes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "trading.proto",
}
